version: "3"

services:
  django:
    build:
      context: ./django
    volumes:
      - ./django:/django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  flask:
    build:
      context: ./Disease_Prediction-main
    volumes:
      - ./Disease_Prediction-main:/Disease_Prediction-main
    ports:
      - "5000:5000"
    command: python app.py

  spring:
    build:
      context: ./disease_back_spring-master
    volumes:
      - ./disease_back_spring-master:/disease_back_spring-master
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    command: mvn spring-boot:run

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
